export const ADD_DATA = 'ADD_DATA'
export const ADD_MARKER = 'ADD_MARKER'
export const CLEAR_MARKERS = 'CLEAR_MARKERS'
export const DELETE_MARKER = 'DELETE_MARKER'
export const GET_MARKERS = 'GET_MARKERS'
